### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by duang33** [nishchaljs/PansharpNet#1]
Hello, does this source code have a corresponding paper for reference？

**Comment by nishchaljs** [comment]
> Hello, does this source code have a corresponding paper for reference？

Hey, the paper will be available on IEEE xplore shortly. I can send a copy to your email if you want!

**Comment by duang33** [comment]
> 
> 
> > Hello, does this source code have a corresponding paper for reference？
> 
> Hey, the paper will be available on IEEE xplore shortly. I can send a copy to your email if you want!

Thank you very much. My email is: 786200310@qq.com

**Comment by nishchaljs** [comment]
https://ieeexplore.ieee.org/document/9544725
Please find the paper here
